-- LAGO: customer-activity history (Domain-brief 7). Same shape as the
-- migration under supabase/migrations — kept in schemas/ as the source
-- of truth for future `supabase db diff` runs.

CREATE TABLE IF NOT EXISTS public.customer_activities_lago (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          bigint NOT NULL
                        REFERENCES public.companies (id) ON DELETE CASCADE,
    visma_activity_key  text UNIQUE,
    visma_aftale_nr     text,
    visma_aktoer_nr     text,
    activity_date       date NOT NULL,
    activity_type_code  int,
    activity_type       text,
    description         text,
    -- Historisk fallback (VISMA-importerede + før 10. sep 2026).
    -- Nye rækker sætter sales_id — sales_name er kun til visning når
    -- der ingen CRM-bruger-modstykke er (fx importerede aktiviteter).
    sales_name          text,
    sales_id            bigint REFERENCES public.sales (id) ON DELETE SET NULL,
    done                boolean NOT NULL DEFAULT true,
    source              text NOT NULL DEFAULT 'visma_import',
    -- Blød sletning (brief 16. sep 2026). Klienten filtrerer på
    -- deleted_at IS NULL i visninger; RPC soft_delete_customer_activity
    -- sætter feltet efter rettighedscheck.
    deleted_at          timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customer_activities_lago_company_date_idx
    ON public.customer_activities_lago (company_id, activity_date DESC);

CREATE INDEX IF NOT EXISTS customer_activities_lago_type_idx
    ON public.customer_activities_lago (activity_type_code);

-- Filter-index for "kun aktive" visninger.
CREATE INDEX IF NOT EXISTS customer_activities_lago_active_company_date_idx
    ON public.customer_activities_lago (company_id, activity_date DESC)
    WHERE deleted_at IS NULL;

ALTER TABLE public.customer_activities_lago ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can read customer_activities_lago"
    ON public.customer_activities_lago
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can insert customer_activities_lago"
    ON public.customer_activities_lago
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can update customer_activities_lago"
    ON public.customer_activities_lago
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can delete customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can delete customer_activities_lago"
    ON public.customer_activities_lago
    FOR DELETE
    TO authenticated
    USING (true);

-- Blød sletning + auto-genberegning af last_visit_at (brief 16. sep 2026)
-- lever i migrationen 20260916100000_lago_soft_delete_activities.sql:
--   - kolonnen deleted_at
--   - RPC soft_delete_customer_activity(id, undo)
--   - trigger customer_activities_lago_recompute_last_visit_at
--
-- Skemaet spejler tabelform, ikke funktion/trigger-body — de tilhører
-- migrationens levetid. Rebuild af skemaet bør derfor ikke droppe RPC
-- eller trigger uden at genanvende dem.
