-- LAGO: kanonisk sælger-/brugerliste (Domain-brief 11).

CREATE TABLE IF NOT EXISTS public.lago_sellers (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visma_sales_code  text UNIQUE NOT NULL,
    full_name         text NOT NULL,
    email             extensions.citext UNIQUE,
    initials          text,
    title             text,
    active            boolean NOT NULL DEFAULT true,
    sales_id          bigint UNIQUE REFERENCES public.sales (id)
                      ON DELETE SET NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS lago_sellers_sales_id_idx
    ON public.lago_sellers (sales_id);

CREATE INDEX IF NOT EXISTS lago_sellers_email_idx
    ON public.lago_sellers (email);

CREATE INDEX IF NOT EXISTS lago_sellers_active_idx
    ON public.lago_sellers (active) WHERE active IS TRUE;

ALTER TABLE public.lago_sellers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read lago_sellers"
    ON public.lago_sellers;
CREATE POLICY "Authenticated users can read lago_sellers"
    ON public.lago_sellers
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Admins can insert lago_sellers"
    ON public.lago_sellers;
CREATE POLICY "Admins can insert lago_sellers"
    ON public.lago_sellers
    FOR INSERT
    TO authenticated
    WITH CHECK (
        auth.uid() IN (
            SELECT user_id FROM public.sales WHERE administrator IS TRUE
        )
    );

DROP POLICY IF EXISTS "Admins can update lago_sellers"
    ON public.lago_sellers;
CREATE POLICY "Admins can update lago_sellers"
    ON public.lago_sellers
    FOR UPDATE
    TO authenticated
    USING (
        auth.uid() IN (
            SELECT user_id FROM public.sales WHERE administrator IS TRUE
        )
    )
    WITH CHECK (
        auth.uid() IN (
            SELECT user_id FROM public.sales WHERE administrator IS TRUE
        )
    );

DROP POLICY IF EXISTS "Admins can delete lago_sellers"
    ON public.lago_sellers;
CREATE POLICY "Admins can delete lago_sellers"
    ON public.lago_sellers
    FOR DELETE
    TO authenticated
    USING (
        auth.uid() IN (
            SELECT user_id FROM public.sales WHERE administrator IS TRUE
        )
    );
