#!/usr/bin/env node
// Reads every prompt under /prompts/*.md and regenerates
// supabase/functions/ai-adapter/prompts/*.ts (one .ts module per .md) plus
// an index.ts that registers them by `${role}.${version}` key.
//
// Why: Supabase Edge Functions only bundle .ts files when compiling for
// runtime, so plain .md files are not reachable via Deno.readTextFile from
// inside the function. The .md files stay the canonical, human-editable
// source; the .ts files are derived build artifacts.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const src = join(repo, "prompts");
const dest = join(repo, "supabase", "functions", "ai-adapter", "prompts");

mkdirSync(dest, { recursive: true });

function parseFrontmatter(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error("missing --- frontmatter --- block");
  const [, fm, body] = m;
  const fields = {};
  for (const line of fm.split("\n")) {
    const i = line.indexOf(":");
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    const value = line
      .slice(i + 1)
      .trim()
      .replace(/^["']|["']$/g, "");
    if (key) fields[key] = value;
  }
  for (const k of ["role", "version", "model"]) {
    if (!fields[k]) throw new Error(`frontmatter missing ${k}`);
  }
  return {
    meta: {
      role: fields.role,
      version: fields.version,
      model: fields.model,
      max_output_tokens: Number(fields.max_output_tokens ?? 1024),
      temperature: Number(fields.temperature ?? 0),
      description: fields.description,
    },
    body: body.trim(),
  };
}

function tsLiteral(value) {
  return JSON.stringify(value);
}

const files = readdirSync(src).filter((f) => f.endsWith(".md"));
const registry = [];

for (const file of files) {
  const raw = readFileSync(join(src, file), "utf8");
  const { meta, body } = parseFrontmatter(raw);
  const moduleName = `${meta.role}.${meta.version}`;
  const tsFile = `${moduleName}.ts`;
  const content =
    `// GENERATED from /prompts/${file} — do not edit by hand.\n` +
    `// Run \`node lago/sync-prompts.mjs\` after changing the .md source.\n` +
    `import type { LoadedPrompt } from "../types.ts";\n\n` +
    `export const prompt: LoadedPrompt = {\n` +
    `  meta: ${tsLiteral(meta)},\n` +
    `  body: ${tsLiteral(body)},\n` +
    `};\n`;
  writeFileSync(join(dest, tsFile), content, "utf8");
  registry.push({ key: moduleName, file: tsFile });
}

const indexContent =
  `// GENERATED by lago/sync-prompts.mjs — do not edit by hand.\n` +
  `import type { LoadedPrompt } from "../types.ts";\n` +
  registry
    .map(
      (r, i) =>
        `import { prompt as p${i} } from "./${r.file.replace(/\.ts$/, ".ts")}";`,
    )
    .join("\n") +
  `\n\nexport const PROMPTS: Record<string, LoadedPrompt> = {\n` +
  registry.map((r, i) => `  ${tsLiteral(r.key)}: p${i},`).join("\n") +
  `\n};\n`;

writeFileSync(join(dest, "index.ts"), indexContent, "utf8");

process.stdout.write(`Generated ${registry.length} prompt module(s):\n`);
for (const r of registry) {
  process.stdout.write(`  ${r.key} -> ${r.file}\n`);
}
