// GENERATED by lago/sync-prompts.mjs — do not edit by hand.
import type { LoadedPrompt } from "../types.ts";
import { prompt as p0 } from "./hello.v1.ts";
import { prompt as p1 } from "./udtraek_fra_besoegsnote.v1.ts";

export const PROMPTS: Record<string, LoadedPrompt> = {
  "hello.v1": p0,
  "udtraek_fra_besoegsnote.v1": p1,
};
