// GENERATED by lago/sync-prompts.mjs — do not edit by hand.
import type { LoadedPrompt } from "../types.ts";
import { prompt as p0 } from "./hello.v1.ts";

export const PROMPTS: Record<string, LoadedPrompt> = {
  "hello.v1": p0,
};
