-- LAGO Domain-brief 7: history table for VISMA-seeded customer
-- activities (besøg, opkald, smagninger, kampagner …). New CRM-native
-- activities will land in the same table with `source = 'crm_native'`
-- once the register-visit flow starts writing rows too. Idempotency key
-- is `visma_activity_key` — a client-side SHA-256 of the composite key
-- (aktør + dato + type + description + medarbejder) since VISMA's
-- Aftalenr is not unique across all rows.

CREATE TABLE IF NOT EXISTS public.customer_activities_lago (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          bigint NOT NULL
                        REFERENCES public.companies (id) ON DELETE CASCADE,
    visma_activity_key  text UNIQUE,
    visma_aftale_nr     text,
    visma_aktoer_nr     text,
    activity_date       date NOT NULL,
    activity_type_code  int,
    activity_type       text,
    description         text,
    sales_name          text,
    done                boolean NOT NULL DEFAULT true,
    source              text NOT NULL DEFAULT 'visma_import',
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customer_activities_lago_company_date_idx
    ON public.customer_activities_lago (company_id, activity_date DESC);

CREATE INDEX IF NOT EXISTS customer_activities_lago_type_idx
    ON public.customer_activities_lago (activity_type_code);

ALTER TABLE public.customer_activities_lago ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can read customer_activities_lago"
    ON public.customer_activities_lago
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can insert customer_activities_lago"
    ON public.customer_activities_lago
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can update customer_activities_lago"
    ON public.customer_activities_lago
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can delete customer_activities_lago"
    ON public.customer_activities_lago;
CREATE POLICY "Authenticated users can delete customer_activities_lago"
    ON public.customer_activities_lago
    FOR DELETE
    TO authenticated
    USING (true);
