-- Brief 89 (28. sep 2026): ordrekommentarer, handlinger og aftalte
-- leveringsdatoer.
--
-- Sælgeren står hos kunden, kunden siger "send Barolo'en nu, hold resten
-- til december". I dag ryger den besked i Teams eller ingen steder.
-- Simon gætter. Denne tabel er sælgerens strukturerede overlevering.
--
-- Formen matcher kunde_aendringsforslag_lago (brief 46) bevidst — samme
-- mønster med hensigt, note, lukning med begrundelse, auto-luk når VISMA
-- viser at handling er sket. Tredje gang mønsteret bruges.
--
-- Datoen ender i VISMA's Ønsket lev. Dato (som LAGO i praksis behandler
-- som aftalt levering — bekraeftet_lev_dato bruges ikke, droppet 4. sep).
-- Vi skriver ikke til VISMA — kommentaren er en instruktion til kontoret.
-- Auto-luk fyrer når importen viser datoen på ordren.

-- 1) Tabel ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ordre_kommentar_lago (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    bigint NOT NULL
                  REFERENCES public.companies (id) ON DELETE CASCADE,
    ordre_nr      text NOT NULL,
    hensigt       text NOT NULL
                  CHECK (hensigt IN (
                      'send_nu',
                      'afvent',
                      'leveringsdato',
                      'ring_kunde',
                      'andet'
                  )),
    -- Kun ved hensigt='leveringsdato'. CHECK constraint sikrer det.
    aftalt_dato   date,
    note          text,
    -- ALTID den handlende (actorSalesId). Under dækning: Jonas, ikke
    -- Camilla — brief 84 §1 "læsning=view, skrivning=actor".
    oprettet_af   bigint REFERENCES public.sales (id) ON DELETE SET NULL,
    oprettet      timestamptz NOT NULL DEFAULT now(),
    status        text NOT NULL DEFAULT 'afventer'
                  CHECK (status IN ('afventer','udfoert','afvist','bortfaldet')),
    lukket        timestamptz,
    lukket_af     bigint REFERENCES public.sales (id) ON DELETE SET NULL,
    lukket_grund  text,
    CONSTRAINT ordre_kommentar_lago_leveringsdato_har_dato
        CHECK (hensigt <> 'leveringsdato' OR aftalt_dato IS NOT NULL),
    CONSTRAINT ordre_kommentar_lago_lukket_konsistent
        CHECK (
            (status = 'afventer' AND lukket IS NULL)
            OR (status <> 'afventer' AND lukket IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS ordre_kommentar_lago_status_idx
    ON public.ordre_kommentar_lago (status, oprettet DESC);
CREATE INDEX IF NOT EXISTS ordre_kommentar_lago_ordre_idx
    ON public.ordre_kommentar_lago (ordre_nr, status);
CREATE INDEX IF NOT EXISTS ordre_kommentar_lago_company_idx
    ON public.ordre_kommentar_lago (company_id, status);

-- 2) Auto-luk-funktion ------------------------------------------------
--
-- Kaldes efter åbne-ordrer-import. Går alle afventende kommentarer
-- igennem, lukker dem hvor virkeligheden allerede er sket:
--
--   'send_nu' + ordren er ikke længere åben (=leveret/lukket) → bortfaldet
--   'send_nu' + antal_faerdigmeldt > 0                        → bortfaldet
--   'leveringsdato' + oensket_leveringsdato = aftalt_dato     → bortfaldet
--
-- Status bliver 'bortfaldet', ikke 'udfoert' — vi ved at virkeligheden
-- har overhalet den, ikke at et menneske handlede på den. lukket_grund
-- gør det klart.
--
-- IKKE koblet til importen endnu. Skrevet nu så den ikke glemmes som
-- Forbrugt blev det (halv-implementering fra 15. sep). Kobles i egen
-- rettelse på importen — dokumenteret som åbent i brief 89.

CREATE OR REPLACE FUNCTION public.close_matched_ordre_kommentarer()
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    r RECORD;
    v_ordre RECORD;
    v_closed int := 0;
BEGIN
    FOR r IN
        SELECT id, ordre_nr, hensigt, aftalt_dato
          FROM public.ordre_kommentar_lago
         WHERE status = 'afventer'
    LOOP
        -- Slå ordren op (kan give NULL hvis ordren er væk fra åbne)
        SELECT antal_faerdigmeldt, oensket_leveringsdato
          INTO v_ordre
          FROM public.open_orders_lago
         WHERE ordre_nr = r.ordre_nr
         LIMIT 1;

        IF r.hensigt = 'send_nu' THEN
            -- Ikke længere åben, eller delvist leveret = handling sket
            IF NOT FOUND
               OR COALESCE(v_ordre.antal_faerdigmeldt, 0) > 0 THEN
                UPDATE public.ordre_kommentar_lago
                   SET status = 'bortfaldet',
                       lukket = now(),
                       lukket_grund =
                         'ordren er ekspederet — set på næste import'
                 WHERE id = r.id;
                v_closed := v_closed + 1;
            END IF;
        ELSIF r.hensigt = 'leveringsdato' THEN
            -- Datoen står nu på ordren i VISMA (via Ønsket lev. Dato)
            IF FOUND
               AND v_ordre.oensket_leveringsdato = r.aftalt_dato THEN
                UPDATE public.ordre_kommentar_lago
                   SET status = 'bortfaldet',
                       lukket = now(),
                       lukket_grund =
                         'aftalt dato står nu på ordren i VISMA'
                 WHERE id = r.id;
                v_closed := v_closed + 1;
            END IF;
        END IF;
        -- 'afvent', 'ring_kunde', 'andet' auto-lukker ikke — kontoret
        -- må selv markere Udført.
    END LOOP;
    RETURN v_closed;
END;
$$;

REVOKE ALL ON FUNCTION public.close_matched_ordre_kommentarer() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.close_matched_ordre_kommentarer()
    TO authenticated;

-- 3) RLS --------------------------------------------------------------
--
-- Alle authenticated læser (både sælger og kontor har brug for at se
-- kommentarer på egne kunder / hele kø'en). Alle authenticated opretter
-- (sælger + kontor kan begge skrive — §5's to-vejs-mønster).
-- UPDATE (status/lukket) er begrænset til kontor+admin — sælgeren kan
-- ikke lukke egne kommentarer, det er kontorets rolle at markere handlet.

ALTER TABLE public.ordre_kommentar_lago ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated read ordre_kommentarer"
    ON public.ordre_kommentar_lago;
CREATE POLICY "Authenticated read ordre_kommentarer"
    ON public.ordre_kommentar_lago
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Authenticated insert ordre_kommentarer"
    ON public.ordre_kommentar_lago;
CREATE POLICY "Authenticated insert ordre_kommentarer"
    ON public.ordre_kommentar_lago
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Kontor/admin update ordre_kommentarer"
    ON public.ordre_kommentar_lago;
CREATE POLICY "Kontor/admin update ordre_kommentarer"
    ON public.ordre_kommentar_lago
    FOR UPDATE TO authenticated
    USING (
      EXISTS (
        SELECT 1 FROM public.sales
         WHERE user_id = auth.uid()
           AND (administrator = true OR lago_role IN ('kontor','admin'))
      )
    )
    WITH CHECK (
      EXISTS (
        SELECT 1 FROM public.sales
         WHERE user_id = auth.uid()
           AND (administrator = true OR lago_role IN ('kontor','admin'))
      )
    );
