-- Domain-brief 27 · "Log ind som" (PO-11).
--
-- Tre stykker:
--
--   1. Revisions-tabel `impersonation_log_lago` — hvem, som hvem, hvornår
--      startet, hvornår afsluttet, hvordan afsluttet. Skrives af Edge
--      Function'en `impersonate` FØR sessionen udleveres, så et nedbrud
--      undervejs ikke kan fjerne sporet.
--
--   2. Guard-funktion `block_write_when_impersonating()` der RAISER
--      hvis auth.jwt() indeholder claim'et 'impersonated_by'. Læselig
--      fejltekst — brugeren skal forstå at det er en spærring, ikke
--      et nedbrud.
--
--   3. Triggeren monteres på alle sælger-skrivbare tabeller. Klienten
--      ved ikke at feltet skal skjules; databasen er sandheden.
--      Sessionen er ægte og kan skrive uden triggeren.

-- 1) Log-tabel

CREATE TABLE IF NOT EXISTS public.impersonation_log_lago (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id   uuid   NOT NULL,
    admin_sales_id  bigint,
    target_user_id  uuid   NOT NULL,
    target_sales_id bigint,
    started_at      timestamptz NOT NULL DEFAULT now(),
    ended_at        timestamptz,
    ended_reason    text CHECK (ended_reason IS NULL
                                OR ended_reason IN ('manual', 'expired', 'unknown')),
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS impersonation_log_started_idx
    ON public.impersonation_log_lago (started_at DESC);

ALTER TABLE public.impersonation_log_lago ENABLE ROW LEVEL SECURITY;

-- Kun admin må læse loggen. Ingen INSERT/UPDATE/DELETE-policy for
-- authenticated — kun Edge Function via service_role (bypasser RLS)
-- skriver til den.
DROP POLICY IF EXISTS "Admins can read impersonation log"
    ON public.impersonation_log_lago;
CREATE POLICY "Admins can read impersonation log"
    ON public.impersonation_log_lago
    FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.sales
            WHERE user_id = auth.uid()
              AND administrator IS TRUE
        )
    );

-- 2) Guard-funktion + trigger

CREATE OR REPLACE FUNCTION public.block_write_when_impersonating()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF (auth.jwt() ->> 'impersonated_by') IS NOT NULL THEN
        RAISE EXCEPTION
            'Skrivning er ikke tilladt under "Log ind som" — sessionen er læse-only. Afslut sessionen og udfør handlingen som dig selv.'
            USING ERRCODE = '42501'; -- insufficient_privilege
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- 3) Monter triggeren på alle skrivbare tabeller.
--
-- To slags dækning:
--
--   a) Sælger-skrivbare (kernen): alt, hvad en sælger kan røre gennem
--      CRM'et — aktiviteter, noter, opgaver, kunder, kontakter,
--      kontakt-noter, deals + deal_notes + tags.
--
--   b) Admin-skrivbare (bælte-og-seler): sales, lago_settings,
--      sales_code_map_lago, lago_sellers, lago_segment_history. En
--      admin kan i teorien ikke være i imperson (Edge Function
--      afviser målet som admin, jf. brief 27-tillæg 16. sep 2026),
--      men triggeren står også her som andet lag — den dag nogen
--      glemmer punkt 1 i Edge Function'en, står punkt 2 stadig.

DO $$
DECLARE
    t text;
    tbls text[] := ARRAY[
        -- Sælger-skrivbare
        'customer_activities_lago',
        'company_notes_lago',
        'tasks',
        'companies',
        'companies_lago',
        'contacts',
        'contacts_lago',
        'contact_notes',
        'deals',
        'deal_notes',
        'tags',
        -- Admin-skrivbare (bælte-og-seler)
        'sales',
        'lago_settings',
        'sales_code_map_lago',
        'lago_sellers',
        'lago_segment_history'
    ];
BEGIN
    FOREACH t IN ARRAY tbls
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS block_write_when_impersonating ON public.%I',
            t
        );
        EXECUTE format(
            'CREATE TRIGGER block_write_when_impersonating '
            'BEFORE INSERT OR UPDATE OR DELETE ON public.%I '
            'FOR EACH ROW EXECUTE FUNCTION public.block_write_when_impersonating()',
            t
        );
    END LOOP;
END $$;

-- 4) RPC til at afslutte en session pænt fra klienten.
--
-- Klienten kan ikke UPDATE-e log-tabellen (ingen policy), så vi
-- eksponerer en SECURITY DEFINER-funktion. Bruges når admin klikker
-- "Afslut" i båndet. Sætter ended_at = now og ended_reason = 'manual'
-- på den seneste åbne session hvor admin_user_id matcher kalderens
-- oprindelige user_id (dvs. den admin-JWT der stadig sidder på
-- kaldet — læses fra impersonated_by-claim'et, hvis sessionen er
-- imperson-token, ellers fra auth.uid()).

CREATE OR REPLACE FUNCTION public.end_impersonation(
    log_id bigint,
    reason text DEFAULT 'manual'
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_actor_user_id uuid;
    v_log RECORD;
BEGIN
    IF reason NOT IN ('manual', 'expired', 'unknown') THEN
        RAISE EXCEPTION 'Ugyldig ended_reason: %', reason;
    END IF;

    -- Hvem er den ægte kalder? Under en imperson-session er
    -- auth.uid() = target-brugeren; den oprindelige admin står i
    -- impersonated_by_user_id-claim'et. Uden det, er kalderen sig
    -- selv (admin der ender fra sin egen session).
    v_actor_user_id := COALESCE(
        (auth.jwt() ->> 'impersonated_by_user_id')::uuid,
        auth.uid()
    );

    SELECT * INTO v_log
    FROM public.impersonation_log_lago
    WHERE id = log_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Impersonation-log % findes ikke', log_id;
    END IF;

    -- Kun den admin, der startede sessionen, må afslutte den.
    IF v_log.admin_user_id IS DISTINCT FROM v_actor_user_id THEN
        RAISE EXCEPTION 'Kun den admin, der startede sessionen, kan afslutte den';
    END IF;

    IF v_log.ended_at IS NOT NULL THEN
        -- Idempotent — allerede afsluttet.
        RETURN;
    END IF;

    UPDATE public.impersonation_log_lago
       SET ended_at = now(),
           ended_reason = reason
     WHERE id = log_id;
END;
$$;

REVOKE ALL ON FUNCTION public.end_impersonation(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.end_impersonation(bigint, text) TO authenticated;
