-- §100 (6. okt 2026): push notification subscriptions.
--
-- One row per user per device. A person with both phone and PC has two.
-- Expired subscriptions (410 Gone from push service) are deleted on send.
--
-- Preferences per user: which notification types they want, per channel
-- (push and/or email). Defaults to all-on for push, all-off for email.

CREATE TABLE IF NOT EXISTS public.push_subscriptions_lago (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_id        bigint NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
    endpoint        text NOT NULL,
    p256dh          text NOT NULL,
    auth            text NOT NULL,
    user_agent      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    -- Unique per endpoint — re-subscribing from same browser overwrites
    UNIQUE (endpoint)
);

CREATE INDEX IF NOT EXISTS push_subscriptions_lago_sales_idx
    ON public.push_subscriptions_lago (sales_id);

ALTER TABLE public.push_subscriptions_lago ENABLE ROW LEVEL SECURITY;

-- Users can read/write their own subscriptions
CREATE POLICY "Own subscriptions read"
    ON public.push_subscriptions_lago FOR SELECT TO authenticated
    USING (sales_id IN (SELECT id FROM public.sales WHERE user_id = auth.uid()));
CREATE POLICY "Own subscriptions insert"
    ON public.push_subscriptions_lago FOR INSERT TO authenticated
    WITH CHECK (sales_id IN (SELECT id FROM public.sales WHERE user_id = auth.uid()));
CREATE POLICY "Own subscriptions delete"
    ON public.push_subscriptions_lago FOR DELETE TO authenticated
    USING (sales_id IN (SELECT id FROM public.sales WHERE user_id = auth.uid()));
-- Service role (edge functions) can read all for sending
CREATE POLICY "Service role read all"
    ON public.push_subscriptions_lago FOR SELECT TO service_role
    USING (true);

-- Notification preferences per user
CREATE TABLE IF NOT EXISTS public.notification_preferences_lago (
    sales_id        bigint NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
    -- What to notify about
    scope           text NOT NULL
                    CHECK (scope IN ('own_tasks', 'own_orders', 'queue')),
    -- For queue scope: which queue (null = all queues the user is in)
    queue_id        bigint REFERENCES public.task_queues_lago(id) ON DELETE CASCADE,
    -- Channels
    push_enabled    boolean NOT NULL DEFAULT true,
    email_enabled   boolean NOT NULL DEFAULT false,
    -- One preference per scope+queue combination
    UNIQUE (sales_id, scope, queue_id)
);

ALTER TABLE public.notification_preferences_lago ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Own preferences"
    ON public.notification_preferences_lago FOR ALL TO authenticated
    USING (sales_id IN (SELECT id FROM public.sales WHERE user_id = auth.uid()))
    WITH CHECK (sales_id IN (SELECT id FROM public.sales WHERE user_id = auth.uid()));

-- Seed default preferences for existing users: all push on, email off
INSERT INTO public.notification_preferences_lago (sales_id, scope)
SELECT s.id, 'own_tasks' FROM public.sales s WHERE s.user_id IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO public.notification_preferences_lago (sales_id, scope)
SELECT s.id, 'own_orders' FROM public.sales s WHERE s.user_id IS NOT NULL
ON CONFLICT DO NOTHING;

-- Queue preferences for each user's queue memberships
INSERT INTO public.notification_preferences_lago (sales_id, scope, queue_id)
SELECT m.sales_id, 'queue', m.queue_id
FROM public.task_queue_members_lago m
ON CONFLICT DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.push_subscriptions_lago TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notification_preferences_lago TO authenticated;
