-- §98-5c (2. okt 2026): task queues.
--
-- Queues are maintained in Settings — name, members, active/inactive.
-- Not hardcoded; more will come. A task sent to a queue belongs to the
-- queue, not a person — anyone in the queue can close it.
--
-- Backoffice already exists as tasks with sales_id=NULL. It becomes the
-- first queue row, and existing NULL-sales_id tasks get queue_id set.

-- 1. Queue table
CREATE TABLE IF NOT EXISTS public.task_queues_lago (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.task_queues_lago ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated read task_queues_lago"
    ON public.task_queues_lago FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage task_queues_lago"
    ON public.task_queues_lago FOR ALL TO authenticated
    USING (auth.uid() IN (SELECT user_id FROM public.sales WHERE administrator IS TRUE))
    WITH CHECK (auth.uid() IN (SELECT user_id FROM public.sales WHERE administrator IS TRUE));

-- 2. Members table
CREATE TABLE IF NOT EXISTS public.task_queue_members_lago (
    queue_id    bigint NOT NULL REFERENCES public.task_queues_lago(id) ON DELETE CASCADE,
    sales_id    bigint NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
    PRIMARY KEY (queue_id, sales_id)
);

ALTER TABLE public.task_queue_members_lago ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated read task_queue_members_lago"
    ON public.task_queue_members_lago FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage task_queue_members_lago"
    ON public.task_queue_members_lago FOR ALL TO authenticated
    USING (auth.uid() IN (SELECT user_id FROM public.sales WHERE administrator IS TRUE))
    WITH CHECK (auth.uid() IN (SELECT user_id FROM public.sales WHERE administrator IS TRUE));

-- 3. queue_id on tasks
ALTER TABLE public.tasks
    ADD COLUMN IF NOT EXISTS queue_id bigint REFERENCES public.task_queues_lago(id) ON DELETE SET NULL;

-- 4. Seed: Backoffice and Marketing
INSERT INTO public.task_queues_lago (name) VALUES ('Backoffice') RETURNING id;
INSERT INTO public.task_queues_lago (name) VALUES ('Marketing') RETURNING id;

-- 5. Marketing members: Rikke and Jonas
-- Find their sales IDs
INSERT INTO public.task_queue_members_lago (queue_id, sales_id)
SELECT q.id, s.id
FROM public.task_queues_lago q, public.sales s
WHERE q.name = 'Marketing'
  AND s.first_name IN ('Rikke', 'Jonas')
ON CONFLICT DO NOTHING;

-- 6. Backoffice members: all kontor-role users
INSERT INTO public.task_queue_members_lago (queue_id, sales_id)
SELECT q.id, s.id
FROM public.task_queues_lago q, public.sales s
WHERE q.name = 'Backoffice'
  AND s.lago_role = 'kontor'
ON CONFLICT DO NOTHING;

-- 7. Existing backoffice tasks: set queue_id
UPDATE public.tasks
SET queue_id = (SELECT id FROM public.task_queues_lago WHERE name = 'Backoffice')
WHERE sales_id IS NULL
  AND queue_id IS NULL;

GRANT SELECT ON public.task_queues_lago TO authenticated;
GRANT SELECT ON public.task_queue_members_lago TO authenticated;
