-- Brief 84 tillæg A §2 (28. sep 2026) — coverage_log_lago
--
-- Audit-log for hvem der passer hvem: "Simon passede Camillas kunder
-- fra 09:12 til 14:31". Adskilt fra impersonation_log_lago med vilje:
-- impersonation har en trigger der BLOKERER writes på 16 tabeller når
-- en session er åben (brief 27). Briefens hele pointe er at dækning
-- IKKE er læse-only — Simon skal kunne registrere besøg, klare
-- opgaver, skrive noter, alt i sit eget navn. Derfor egen tabel,
-- ingen trigger, ingen skrive-guard.
--
-- Tillæg A §1: "alle må passe alle". Ingen rolle-check her, ingen
-- rettigheds-liste. Loggen rekonstruerer hvem der arbejdede i hvis
-- portefølje — den spærrer ingen fra det.
--
-- Tillæg A §2: "alle handlinger i CRM skal logges". Ingen af de tre
-- eksisterende log-tabeller passede: lago_activity_log er en VIEW for
-- entitetshændelser (uden hvem-gjorde-det); activity_log_view findes
-- ikke; task_events_lago er task-specifik. Dækning er ikke task-
-- specifik og ikke entitetshændelse — den er session-metadata.

CREATE TABLE IF NOT EXISTS public.coverage_log_lago (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    covering_user_id   uuid   NOT NULL,
    covering_sales_id  bigint,
    covered_user_id    uuid   NOT NULL,
    covered_sales_id   bigint,
    started_at         timestamptz NOT NULL DEFAULT now(),
    ended_at           timestamptz,
    ended_reason       text CHECK (ended_reason IS NULL
                                   OR ended_reason IN ('manual', 'session_end', 'unknown')),
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS coverage_log_lago_started_idx
    ON public.coverage_log_lago (started_at DESC);
CREATE INDEX IF NOT EXISTS coverage_log_lago_covering_open_idx
    ON public.coverage_log_lago (covering_user_id)
    WHERE ended_at IS NULL;

COMMENT ON TABLE public.coverage_log_lago IS
    'Brief 84 tillæg A §2 (28. sep 2026): hvem passede hvem, hvornår. '
    'IKKE impersonation — dækning er skrive-tilladt: Simon arbejder i '
    'sit eget navn i Camillas portefølje. Ingen write-guard. '
    'VIGTIGT for læsere: ended_at IS NULL betyder "ikke afsluttet '
    'eksplicit", IKKE "foregår lige nu". PortefoljeProvider lukker '
    'brugerens egne åbne rækker ældre end 12 timer ved app-start med '
    'ended_reason=unknown (brief 84 opfølgning D). En dækning der '
    'sluttede kl 10 uden tryk på "Tilbage til mine" står derfor åben '
    'til næste app-start dagen efter. Bygger man senere "hvem passer '
    'hvem lige nu", er ended_at IS NULL ikke svaret — join i stedet '
    'mod aktive klient-sessioner eller sæt en snævrere tærskel.';

COMMENT ON COLUMN public.coverage_log_lago.covering_user_id IS
    'Den handlende (Simon). auth.uid() på RLS-check ved INSERT.';
COMMENT ON COLUMN public.coverage_log_lago.covered_user_id IS
    'Den, hvis portefølje der arbejdes i (Camilla).';

ALTER TABLE public.coverage_log_lago ENABLE ROW LEVEL SECURITY;

-- Alle authenticated må læse — brief 84 tillæg A §1: gennemsigtighed i
-- et hus med seks mennesker er billigere end et rettighedssystem
-- ingen vedligeholder.
DROP POLICY IF EXISTS "Authenticated read coverage_log_lago"
    ON public.coverage_log_lago;
CREATE POLICY "Authenticated read coverage_log_lago"
    ON public.coverage_log_lago FOR SELECT TO authenticated USING (true);

-- INSERT: kun egen række — covering_user_id skal være auth.uid().
-- Samme regel som task_events_lago's event_af.
DROP POLICY IF EXISTS "Authenticated insert own coverage_log_lago"
    ON public.coverage_log_lago;
CREATE POLICY "Authenticated insert own coverage_log_lago"
    ON public.coverage_log_lago FOR INSERT TO authenticated
    WITH CHECK (covering_user_id = auth.uid());

-- UPDATE: kun for at lukke egen åbne session. Ikke muligt at ændre
-- covered_user_id, started_at eller andre felter — det ville rewrite
-- historik.
DROP POLICY IF EXISTS "Authenticated close own coverage_log_lago"
    ON public.coverage_log_lago;
CREATE POLICY "Authenticated close own coverage_log_lago"
    ON public.coverage_log_lago FOR UPDATE TO authenticated
    USING (covering_user_id = auth.uid() AND ended_at IS NULL)
    WITH CHECK (covering_user_id = auth.uid());
