-- Brief 46 (16. sep 2026): dataforbedring — kø for ændringsforslag
-- til VISMA-ejede felter.
--
-- Logik-nøglen står i §1 og gentages i færdig-krav 2: forslaget skal
-- lukke sig selv efter en import matcher værdien. Uden auto-luk bliver
-- feltet en kø, der aldrig ryddes, og folk holder op med at foreslå
-- noget.
--
-- Tre stykker:
--   1) Tabel — feltnavn + værdi gemmes hver for sig så
--      close_matched_change_suggestions kan sammenligne
--   2) close_matched_change_suggestions() — kaldes efter kunde-import,
--      lukker alle afventende forslag hvor VISMA-værdien nu matcher
--      det foreslåede
--   3) RLS-policies — alle authenticated kan læse (kontor + sælger),
--      alle kan oprette, kun kontor/admin kan opdatere status.

-- 1) Tabel ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.kunde_aendringsforslag_lago (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         bigint NOT NULL
                       REFERENCES public.companies (id) ON DELETE CASCADE,
    /** Feltnavn — matcher enten companies.<name> eller
     *  companies_lago.<name>. Se felt_source-kolonnen for hvilken. */
    felt               text NOT NULL,
    /** Peger på tabellen der ejer feltet. 'companies' eller
     *  'companies_lago'. Bruges af close_matched_change_suggestions
     *  til at slå den aktuelle værdi op i den rigtige tabel. */
    felt_source        text NOT NULL DEFAULT 'companies'
                       CHECK (felt_source IN ('companies','companies_lago')),
    nuvaerende_vaerdi  text,
    foreslaaet_vaerdi  text NOT NULL,
    note               text,
    foreslaaet_af      bigint REFERENCES public.sales (id) ON DELETE SET NULL,
    oprettet           timestamptz NOT NULL DEFAULT now(),
    status             text NOT NULL DEFAULT 'afventer'
                       CHECK (status IN ('afventer','gennemfoert','afvist')),
    lukket             timestamptz,
    lukket_af          bigint REFERENCES public.sales (id) ON DELETE SET NULL,
    lukket_grund       text
);

-- To sælgere skal ikke kunne foreslå det samme på samme felt samtidig.
-- Partial unique index tillader flere afventende KUN forskellige felter,
-- men blokerer et andet aktivt forslag på samme (company, felt).
CREATE UNIQUE INDEX IF NOT EXISTS kunde_aendringsforslag_lago_one_open_per_field
    ON public.kunde_aendringsforslag_lago (company_id, felt)
    WHERE status = 'afventer';

CREATE INDEX IF NOT EXISTS kunde_aendringsforslag_lago_status_idx
    ON public.kunde_aendringsforslag_lago (status, oprettet DESC);

-- 2) Auto-luk-funktion ------------------------------------------------

-- Kaldes efter kundeimporten er kørt. Går alle afventende forslag
-- igennem, slår den aktuelle værdi op i den ejende tabel via dynamic
-- SQL, sammenligner med foreslaaet_vaerdi, lukker match. Trim +
-- lower-case sammenligning så "33 12 10 55" og "33 12 10 55 " matcher.
--
-- SECURITY DEFINER så importens sales_id ikke kræver kontor-adgang;
-- funktionen er intern og kan kun kaldes fra authenticated (og hverken
-- opretter eller sletter data — kun UPDATE status).
CREATE OR REPLACE FUNCTION public.close_matched_change_suggestions()
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    r RECORD;
    v_actual text;
    v_sql text;
    v_closed int := 0;
BEGIN
    FOR r IN
        SELECT id, company_id, felt, felt_source, foreslaaet_vaerdi
          FROM public.kunde_aendringsforslag_lago
         WHERE status = 'afventer'
    LOOP
        IF r.felt_source = 'companies' THEN
            v_sql := format(
                'SELECT %I::text FROM public.companies WHERE id = $1',
                r.felt
            );
        ELSE
            v_sql := format(
                'SELECT %I::text FROM public.companies_lago WHERE company_id = $1',
                r.felt
            );
        END IF;
        BEGIN
            EXECUTE v_sql INTO v_actual USING r.company_id;
        EXCEPTION WHEN OTHERS THEN
            -- Ukendt kolonnenavn i tabellen — spring over stille.
            -- Forslaget bliver hængende afventende indtil admin
            -- retter felt-navnet eller afviser det manuelt.
            CONTINUE;
        END;
        IF v_actual IS NOT NULL
           AND lower(btrim(v_actual)) = lower(btrim(r.foreslaaet_vaerdi)) THEN
            UPDATE public.kunde_aendringsforslag_lago
               SET status = 'gennemfoert',
                   lukket = now(),
                   lukket_grund = 'rettet i VISMA'
             WHERE id = r.id;
            v_closed := v_closed + 1;
        END IF;
    END LOOP;
    RETURN v_closed;
END;
$$;

REVOKE ALL ON FUNCTION public.close_matched_change_suggestions() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.close_matched_change_suggestions()
    TO authenticated;

-- 3) RLS --------------------------------------------------------------

ALTER TABLE public.kunde_aendringsforslag_lago ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated read change suggestions"
    ON public.kunde_aendringsforslag_lago;
CREATE POLICY "Authenticated read change suggestions"
    ON public.kunde_aendringsforslag_lago
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Authenticated insert change suggestions"
    ON public.kunde_aendringsforslag_lago;
CREATE POLICY "Authenticated insert change suggestions"
    ON public.kunde_aendringsforslag_lago
    FOR INSERT TO authenticated WITH CHECK (true);

-- Update kun til kontor + admin. Sælger kan ikke lukke egen foreslag
-- direkte — kontoret gør det via "Markér rettet"-knappen, eller
-- close_matched_change_suggestions gør det automatisk.
DROP POLICY IF EXISTS "Kontor/admin update change suggestions"
    ON public.kunde_aendringsforslag_lago;
CREATE POLICY "Kontor/admin update change suggestions"
    ON public.kunde_aendringsforslag_lago
    FOR UPDATE TO authenticated
    USING (
      EXISTS (
        SELECT 1 FROM public.sales
         WHERE user_id = auth.uid()
           AND (administrator = true OR lago_role IN ('kontor','admin'))
      )
    )
    WITH CHECK (
      EXISTS (
        SELECT 1 FROM public.sales
         WHERE user_id = auth.uid()
           AND (administrator = true OR lago_role IN ('kontor','admin'))
      )
    );
