-- §99 (2. okt 2026): order follow-up status for the office.
--
-- Three actions the office can take on an open order:
--   1. Send to salesperson for follow-up (creates a task)
--   2. Mark as "status changed in VISMA" (awaits import confirmation)
--   3. Postpone follow-up (with a new deadline)
--
-- The status drives the icon and sort position on the order list.
-- The urgency color is derived from the bucket + date + status.

CREATE TABLE IF NOT EXISTS public.ordre_opfoelgning_lago (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordre_nr        text NOT NULL,
    company_id      bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,

    -- What was done
    handling        text NOT NULL
                    CHECK (handling IN (
                        'sendt_til_saelger',
                        'afventer_visma',
                        'udskudt'
                    )),

    -- Who did it
    oprettet_af     bigint REFERENCES public.sales(id) ON DELETE SET NULL,
    oprettet        timestamptz NOT NULL DEFAULT now(),

    -- Deadline (when the action expires and the order returns to top)
    frist           date,

    -- For sendt_til_saelger: which salesperson + the task_id created
    sendt_til       bigint REFERENCES public.sales(id) ON DELETE SET NULL,
    task_id         bigint REFERENCES public.tasks(id) ON DELETE SET NULL,

    -- Resolution
    status          text NOT NULL DEFAULT 'aktiv'
                    CHECK (status IN ('aktiv', 'bekraeftet', 'udloebet', 'annulleret')),
    lukket          timestamptz,

    -- Note (optional reason for postponement etc.)
    note            text
);

CREATE INDEX IF NOT EXISTS ordre_opfoelgning_lago_ordre_idx
    ON public.ordre_opfoelgning_lago (ordre_nr);
CREATE INDEX IF NOT EXISTS ordre_opfoelgning_lago_company_idx
    ON public.ordre_opfoelgning_lago (company_id);
CREATE INDEX IF NOT EXISTS ordre_opfoelgning_lago_aktiv_idx
    ON public.ordre_opfoelgning_lago (status, frist)
    WHERE status = 'aktiv';

COMMENT ON TABLE public.ordre_opfoelgning_lago IS
'§99 (2. okt 2026): office follow-up actions on open orders. Drives icon (↗/⏱/◷), '
'urgency color, and sort position. Three actions: send to salesperson, mark as changed '
'in VISMA (awaits import confirmation), postpone. Active actions with expired deadlines '
'return to top and turn red.';

ALTER TABLE public.ordre_opfoelgning_lago ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated read ordre_opfoelgning"
    ON public.ordre_opfoelgning_lago FOR SELECT TO authenticated USING (true);
CREATE POLICY "Kontor/admin write ordre_opfoelgning"
    ON public.ordre_opfoelgning_lago FOR INSERT TO authenticated
    WITH CHECK (
        auth.uid() IN (
            SELECT user_id FROM public.sales
            WHERE administrator IS TRUE OR lago_role = 'kontor'
        )
    );
CREATE POLICY "Kontor/admin update ordre_opfoelgning"
    ON public.ordre_opfoelgning_lago FOR UPDATE TO authenticated
    USING (
        auth.uid() IN (
            SELECT user_id FROM public.sales
            WHERE administrator IS TRUE OR lago_role = 'kontor'
        )
    );
